# Generated by Django 3.2 on 2021-05-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
