# Generated by Django 3.2 on 2021-05-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
